version: '3'

services:
  todotests:
    image: todotests
    build: ./todo-app/tests/
    environment:
      - FRONT_HOST=todofront
    depends_on:
        - todoback
        - todofront

  todofront:
    image: todofrontend
    build: ./todo-app/front-end/
    environment:
        - REACT_APP_API_HOST=todoback
    ports:
        - 3000:3000
    depends_on:
        - todoback

  todoback:
    image: todobackend
    build: ./todo-app/back-end/
    ports:
      - 3001:3001